### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by acabal** [cncoulter/roswitha_the-plays-of-roswitha#1]
- Translator's notes:

  - Missing `<abbr class="name">` around abbreviated first names

  - `<li>` items require a direct child `<p>`

  - OSB missing `class="initialism"`, and remove periods

- Dedication: `<header>` should contain `<h2>`. You can put the "to" `<p>` right after the `<h2>` in the header.

- Intro: byline is not a subtitle. Instead, add a `<header>` tag and move `<h2>` into it. Then the byline can be a `<p>` after the `<h2>`.

- Same in foreword

- In dramatis personae, don't use `<ul><li>` to offset descriptors of the characters. `<li>` means "list item" which those are not. Instead, you can just use a new `<p>` and target it for plain styling with `[epub|type~="z3998:dramatis-personae"] li p + p{ font-style: normal; }`

 - In Gallicanus dramatis personae, instead of having two separate sections that are both "dramatis personae", I would arrange them so that there is one `<section>` that has the dramatis-personae semantic with an `<h3>` titled "Characters" for consistency with the rest of the D-Ps. Then, add two sub-`<section>`s for "characters in part 1" and 2. Those two headers are part of the same parent unit, I think, instead of being adjacent units. (I.e. in print they would appear on the same page and not on separate pages.) 

- note.xhtml should have the filename "afterword.xhtml". Remember to do a find-and-replace in the project for that filename.

- Endnotes: "ego, clamor validus Gandeishermensis" should be in `<i xml:lang="la">`

- Content.opf: Roswitha needs the additional MARC attribute of wpr (writer of preface)

- In local.css line 81, can you change the naked `:first-child` selector to `p:first-child`? Yours is technically correct but ereaders have notoriously poor CSS support and we want to make it as easy for them as possible.

**Comment by cncoulter** [comment]
Thanks for the notes! I've fixed all of those. Please let me know if there are any more issues.

Note: In dramatis personae, I had used `<ul><li>` to offset descriptors of the characters because that's how I saw it handled in _Ghosts_ by Henrik Ibsen: <https://github.com/standardebooks/henrik-ibsen_ghosts_william-archer/blob/master/src/epub/text/characters.xhtml>. That might be an issue we need to fix in that book also, unless there's something I'm missing.

**Comment by acabal** [comment]
I see, that's definitely incorrect in Ibsen. I've gone ahead and fixed it.

Great work and let the mailing list know if you'd like to work on something else!
